os: linux
sudo: required
language: "minimal"
services:
  - docker
env:
  - DOCKER_IMAGE="toliak/bootstrap-cpp"

before_script:
  - docker pull $DOCKER_IMAGE

jobs:
  include:
    - name: "coverage"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/coverage.sh $DOCKER_IMAGE
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh
    - name: "tests"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/tests.sh $DOCKER_IMAGE
    - name: "genev"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/genenv.sh $DOCKER_IMAGE

notifications:
email: false